import { SessionProvider } from "next-auth/react"


import ModalProvider from '@/components/provider/provider-modal'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'




import { ThemeProvider } from '@/components/provider/theme-provider'

import { getServerSession } from "next-auth/next"
import Provider from "@/components/provider/client-session-provider"
import { SocketProvider } from "@/components/provider/socket-provider"


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (


    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Provider>
            <SocketProvider>
              <ModalProvider />
              {children}
            </SocketProvider>
          </Provider>
        </ThemeProvider>
      </body>

    </html>
  )
}
